name: Auto Assign Issues to Organization Project

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign-issue-to-project:
    runs-on: ubuntu-latest
    name: Assign Issue to Project
    steps:
      - name: Assign Issue to Project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened'
        with:
          project: "https://github.com/orgs/symptomizer/projects/1"
